name: Deploy WordPress with Logo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install WordPress
      run: |
        # Download WordPress
        curl -O https://wordpress.org/latest.tar.gz
        tar -xzf latest.tar.gz
        mv wordpress/* ./
        rm -rf wordpress latest.tar.gz

        # Create wp-config.php
        cp wp-config-sample.php wp-config.php
        sed -i "s/database_name_here/${{ secrets.DB_NAME }}/" wp-config.php
        sed -i "s/username_here/${{ secrets.DB_USER }}/" wp-config.php
        sed -i "s/password_here/${{ secrets.DB_PASSWORD }}/" wp-config.php
        sed -i "s/localhost/${{ secrets.DB_HOST }}/" wp-config.php

        # Set up file permissions
        chown -R www-data:www-data ./
        chmod -R 755 ./

        # Install WP-CLI
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        mv wp-cli.phar /usr/local/bin/wp

        # Install WordPress
        wp core install --url=${{ secrets.SITE_URL }} --title="My WordPress Site" --admin_user=${{ secrets.ADMIN_USER }} --admin_password=${{ secrets.ADMIN_PASSWORD }} --admin_email=${{ secrets.ADMIN_EMAIL }}

    - name: Upload Logo
      run: |
        # Upload logo
        mkdir -p wp-content/themes/twentytwentyone-child/images
        cp assets/logo.png wp-content/themes/twentytwentyone-child/images/logo.png

        # Update theme to use the logo
        cat << 'EOF' >> wp-content/themes/twentytwentyone-child/functions.php
        function my_theme_setup() {
            add_theme_support( 'custom-logo' );
        }
        add_action( 'after_setup_theme', 'my_theme_setup' );

        function my_custom_logo() {
            the_custom_logo();
        }
        add_action( 'wp_head', 'my_custom_logo' );
        EOF
